# 网关端口
server:
  port: 8888
#  应用名称
spring:
  application:
    name: gateway
# eureka注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
# 路由配置
zuul:
  routes:
    xx:
      path:
      serviceId: